### ISSUE TITLE
should fail with a message when the browser does not support WebGPU

### ISSUE THREAD

**Issue by dneto0** [reeselevine/webgpu-litmus#13]
If I run a test with production Chrome (version 91), I get a spinny icon as if it's loading something.

But Chrome 91 doesn't support WebGPU.  Please have the page show an error if trying to run a test when WebGPU is not supported.

**Comment by reeselevine** [comment]
Thanks for the first issue! As a quick fix I added an alert in this commit: https://github.com/reeselevine/webgpu-litmus/commit/adc2a7e40eb01e42f6bb56713fc1a68cbad932ab

We might want to make this more sophisticated later on, but closing this issue for now.
